import type { ThemeDefinition } from 'vuetify'

export const staticPrimaryColor = '#0F56D9'
export const staticPrimaryDarkenColor = '#0A3F9E'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': '#64748B',
      'secondary-darken-1': '#475569',
      'on-secondary': '#fff',
      'success': '#16803C',
      'success-darken-1': '#116932',
      'on-success': '#fff',
      'info': '#0875D1',
      'info-darken-1': '#075FA8',
      'on-info': '#fff',
      'warning': '#B7791F',
      'warning-darken-1': '#9A6218',
      'on-warning': '#fff',
      'error': '#B42318',
      'error-darken-1': '#912018',
      'on-error': '#fff',
      'background': '#F6F8FB',
      'on-background': '#172033',
      'surface': '#fff',
      'on-surface': '#172033',
      'grey-50': '#FAFAFA',
      'grey-100': '#F5F5F5',
      'grey-200': '#EEEEEE',
      'grey-300': '#E0E0E0',
      'grey-400': '#BDBDBD',
      'grey-500': '#9E9E9E',
      'grey-600': '#757575',
      'grey-700': '#616161',
      'grey-800': '#424242',
      'grey-900': '#212121',
      'perfect-scrollbar-thumb': '#CBD5E1',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#fafafa',
      'track-bg': '#EEF2F7',
      'chat-bg': '#F8FAFC',
    },

    variables: {
      'code-color': '#0F56D9',
      'overlay-scrim-background': '#172033',
      'tooltip-background': '#172033',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#172033',
      'border-opacity': 0.12,
      'table-header-color': '#F1F5F9',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,

      // 👉 shadows
      'shadow-key-umbra-color': '#0F172A',
      'shadow-xs-opacity': '0.08',
      'shadow-sm-opacity': '0.10',
      'shadow-md-opacity': '0.12',
      'shadow-lg-opacity': '0.14',
      'shadow-xl-opacity': '0.16',
    },
  },

  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': '#94A3B8',
      'secondary-darken-1': '#64748B',
      'on-secondary': '#fff',
      'success': '#4ADE80',
      'success-darken-1': '#22C55E',
      'on-success': '#fff',
      'info': '#60A5FA',
      'info-darken-1': '#3B82F6',
      'on-info': '#fff',
      'warning': '#FBBF24',
      'warning-darken-1': '#F59E0B',
      'on-warning': '#fff',
      'error': '#F87171',
      'error-darken-1': '#EF4444',
      'on-error': '#fff',
      'background': '#0D1117',
      'on-background': '#E7E3FC',
      'surface': '#151B23',
      'on-surface': '#E7E3FC',
      'grey-50': '#2A2E42',
      'grey-100': '#2F3349',
      'grey-200': '#4A5072',
      'grey-300': '#5E6692',
      'grey-400': '#7983BB',
      'grey-500': '#8692D0',
      'grey-600': '#AAB3DE',
      'grey-700': '#B6BEE3',
      'grey-800': '#CFD3EC',
      'grey-900': '#E7E9F6',
      'perfect-scrollbar-thumb': '#4a5072',
      'skin-bordered-background': '#312d4b',
      'skin-bordered-surface': '#312d4b',
      'expansion-panel-text-custom-bg': '#373350',
      'track-bg': '#474360',
      'chat-bg': '#373452',
    },

    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': '#312D4B',
      'tooltip-background': '#F7F4FF',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'disabled-opacity': 0.4,
      'dragged-opacity': 0.1,
      'border-color': '#E7E3FC',
      'border-opacity': 0.12,
      'table-header-color': '#3D3759',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,

      // 👉 Shadows
      'shadow-key-umbra-color': '#131120',
      'shadow-xs-opacity': '0.20',
      'shadow-sm-opacity': '0.22',
      'shadow-md-opacity': '0.24',
      'shadow-lg-opacity': '0.26',
      'shadow-xl-opacity': '0.28',
    },
  },
}

export default themes
