// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderSalesService.Infrastructure.Data;

#nullable disable

namespace OrderSalesService.Infrastructure.Migrations
{
    [DbContext(typeof(OrderSalesDbContext))]
    [Migration("20260626144244_AddCashTransactions")]
    partial class AddCashTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderSalesService.Application.Models.CashShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExpectedCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OpeningCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Variance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ShiftCode")
                        .IsUnique()
                        .HasDatabaseName("IX_CashShifts_ShiftCode");

                    b.HasIndex("CashierId", "Status")
                        .HasDatabaseName("IX_CashShifts_Cashier_Status");

                    b.ToTable("CashShifts", (string)null);
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.CashTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceOrRecipient")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CashTransactions", (string)null);
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DebtAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPurchased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_Code");

                    b.HasIndex("CustomerGroupId");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000001-1111-2222-3333-444455556666"),
                            Address = "123 Đường Láng, Đống Đa, Hà Nội",
                            Code = "KH001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerGroupId = new Guid("c24f74d1-55b2-4d2a-8742-5f657a8a25c1"),
                            DebtAmount = 0m,
                            Email = "vananh@gmail.com",
                            FullName = "Nguyễn Văn Anh",
                            IsActive = true,
                            Note = "Khách hàng lẻ thân quen",
                            Phone = "0912345678",
                            TotalPurchased = 0m
                        },
                        new
                        {
                            Id = new Guid("d0000002-1111-2222-3333-444455556666"),
                            Address = "456 Nguyễn Trãi, Thanh Xuân, Hà Nội",
                            Code = "KH002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerGroupId = new Guid("e5f02c6b-67a8-44a6-b51f-4b07fb7b4de1"),
                            DebtAmount = 0m,
                            Email = "thibinh@gmail.com",
                            FullName = "Trần Thị Bình",
                            IsActive = true,
                            Note = "Khách hàng VIP mua nhiều",
                            Phone = "0987654321",
                            TotalPurchased = 1500000m
                        },
                        new
                        {
                            Id = new Guid("d0000003-1111-2222-3333-444455556666"),
                            Address = "789 Lê Lợi, Quận 1, TP. Hồ Chí Minh",
                            Code = "KH003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerGroupId = new Guid("b8e18df0-fc7c-4869-9528-765f14841db1"),
                            DebtAmount = 2000000m,
                            Email = "hoangcuong@gmail.com",
                            FullName = "Lê Hoàng Cường",
                            IsActive = true,
                            Note = "Đại lý bán sỉ tạp hóa nhỏ",
                            Phone = "0905123456",
                            TaxCode = "8012345678",
                            TotalPurchased = 12000000m
                        },
                        new
                        {
                            Id = new Guid("d0000004-1111-2222-3333-444455556666"),
                            Address = "101 Cầu Giấy, Quan Hoa, Hà Nội",
                            Code = "KH004",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerGroupId = new Guid("c24f74d1-55b2-4d2a-8742-5f657a8a25c1"),
                            DebtAmount = 0m,
                            Email = "minhduc@gmail.com",
                            FullName = "Phạm Minh Đức",
                            IsActive = true,
                            Note = "Khách vãng lai mua lẻ",
                            Phone = "0936789012",
                            TotalPurchased = 300000m
                        },
                        new
                        {
                            Id = new Guid("d0000005-1111-2222-3333-444455556666"),
                            Address = "202 Trần Hưng Đạo, Hoàn Kiếm, Hà Nội",
                            Code = "KH005",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerGroupId = new Guid("e5f02c6b-67a8-44a6-b51f-4b07fb7b4de1"),
                            DebtAmount = 0m,
                            Email = "thuha@gmail.com",
                            FullName = "Đỗ Thu Hà",
                            IsActive = true,
                            Note = "Khách hàng VIP mua hàng tháng",
                            Phone = "0977111222",
                            TotalPurchased = 2500000m
                        });
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.CustomerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DefaultDiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("CustomerGroups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f02c6b-67a8-44a6-b51f-4b07fb7b4de1"),
                            DefaultDiscountPercent = 10.0m,
                            Name = "VIP",
                            Note = "Khách hàng VIP - Chiết khấu 10%"
                        },
                        new
                        {
                            Id = new Guid("c24f74d1-55b2-4d2a-8742-5f657a8a25c1"),
                            DefaultDiscountPercent = 0.0m,
                            Name = "Khách Lẻ",
                            Note = "Khách hàng lẻ - Không chiết khấu"
                        },
                        new
                        {
                            Id = new Guid("b8e18df0-fc7c-4869-9528-765f14841db1"),
                            DefaultDiscountPercent = 15.0m,
                            Name = "Khách Sỉ",
                            Note = "Khách hàng sỉ - Chiết khấu 15%"
                        });
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("DebtAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PromotionCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PromotionDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PromotionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Orders_OrderCode");

                    b.HasIndex("CustomerId", "CreatedAt")
                        .HasDatabaseName("IX_Orders_CustomerId_CreatedAt");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("IX_OrderStatusHistories_OrderId_CreatedAt");

                    b.ToTable("OrderStatusHistories", (string)null);
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ReceivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceivedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.ProcessedEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedEvents", (string)null);
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PromotionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Promotions_Code");

                    b.HasIndex("IsActive", "StartAt", "EndAt")
                        .HasDatabaseName("IX_Promotions_Active_DateRange");

                    b.ToTable("Promotions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-1111-2222-3333-444455556666"),
                            Code = "MUNGKHAITRUONG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Description = "Giảm giá 5% cho toàn bộ đơn hàng trị giá từ 100,000 VND trở lên",
                            DiscountType = "Percent",
                            DiscountValue = 5m,
                            EndAt = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumOrderAmount = 100000m,
                            Name = "Mừng Khai Trương Siêu Thị",
                            PromotionType = "OrderDiscount",
                            StartAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000002-1111-2222-3333-444455556666"),
                            Code = "TRIANKHACHHANG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Description = "Giảm giá 10% cho toàn bộ đơn hàng trị giá từ 200,000 VND trở lên",
                            DiscountType = "Percent",
                            DiscountValue = 10m,
                            EndAt = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumOrderAmount = 200000m,
                            Name = "Tri Ân Khách Hàng Thân Thiết",
                            PromotionType = "OrderDiscount",
                            StartAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.PromotionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequiredQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionItems", (string)null);
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.ReturnOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReturnCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalRefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_ReturnOrders_OrderId");

                    b.ToTable("ReturnOrders", (string)null);
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.ReturnOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReturnOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReturnQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReturnOrderId");

                    b.ToTable("ReturnOrderDetails", (string)null);
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DebtAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Suppliers_Code");

                    b.ToTable("Suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0000001-1111-2222-3333-444455556666"),
                            Address = "Lô II-3, Đường số 11, KCN Tân Bình, Tân Phú, TP. HCM",
                            Code = "NCC-ACECOOK",
                            ContactEmail = "info@acecookvietnam.com",
                            ContactPerson = "Ông Kajiwara Junichi",
                            ContactPhone = "02838154060",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            DebtAmount = 0m,
                            IsActive = true,
                            Name = "Công ty Cổ phần Acecook Việt Nam",
                            Note = "Nhà cung cấp các loại mì ăn liền Hảo Hảo",
                            TaxCode = "0303525911"
                        },
                        new
                        {
                            Id = new Guid("e0000002-1111-2222-3333-444455556666"),
                            Address = "Lô A2-3, KCN Tây Bắc Củ Chi, Củ Chi, TP. HCM",
                            Code = "NCC-UNILEVER",
                            ContactEmail = "tuvankhachhang@unilever.com",
                            ContactPerson = "Bà Nguyễn Thị Bích Vân",
                            ContactPhone = "02854131100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            DebtAmount = 15000000m,
                            IsActive = true,
                            Name = "Công ty TNHH Unilever Việt Nam",
                            Note = "Nhà cung cấp Sunlight, OMO, Clear, Lifebuoy...",
                            TaxCode = "0301438692"
                        },
                        new
                        {
                            Id = new Guid("e0000003-1111-2222-3333-444455556666"),
                            Address = "10 Tân Trào, Tân Phú, Quận 7, TP. HCM",
                            Code = "NCC-VINAMILK",
                            ContactEmail = "vinamilk@vinamilk.com.vn",
                            ContactPerson = "Bà Mai Kiều Liên",
                            ContactPhone = "02854155555",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            DebtAmount = 0m,
                            IsActive = true,
                            Name = "Công ty Cổ phần Sữa Việt Nam (Vinamilk)",
                            Note = "Nhà cung cấp các sản phẩm sữa tươi, sữa chua, sữa đặc",
                            TaxCode = "0300588569"
                        },
                        new
                        {
                            Id = new Guid("e0000004-1111-2222-3333-444455556666"),
                            Address = "Cao ốc Sheraton, 88 Đồng Khởi, Quận 1, TP. HCM",
                            Code = "NCC-PEPSICO",
                            ContactEmail = "contact@suntorypepsico.vn",
                            ContactPerson = "Ông Jahanzeb Khan",
                            ContactPhone = "02838219468",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            DebtAmount = 8000000m,
                            IsActive = true,
                            Name = "Công ty TNHH Suntory PepsiCo Việt Nam",
                            Note = "Nhà cung cấp Pepsi, 7Up, Aquafina, Sting...",
                            TaxCode = "0312051832"
                        },
                        new
                        {
                            Id = new Guid("e0000005-1111-2222-3333-444455556666"),
                            Address = "Tầng 18, Tòa nhà Vietcombank, 5 Công Trường Mê Linh, Quận 1, TP. HCM",
                            Code = "NCC-HEINEKEN",
                            ContactEmail = "heinekenvietnam@heineken.com",
                            ContactPerson = "Ông Alexander Koch",
                            ContactPhone = "02838222755",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            DebtAmount = 0m,
                            IsActive = true,
                            Name = "Công ty TNHH Nhà Máy Bia Heineken Việt Nam",
                            Note = "Nhà cung cấp bia Heineken, Tiger, Larue...",
                            TaxCode = "0300830053"
                        });
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.Customer", b =>
                {
                    b.HasOne("OrderSalesService.Application.Models.CustomerGroup", "CustomerGroup")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomerGroup");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.Order", b =>
                {
                    b.HasOne("OrderSalesService.Application.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.OrderDetail", b =>
                {
                    b.HasOne("OrderSalesService.Application.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.OrderStatusHistory", b =>
                {
                    b.HasOne("OrderSalesService.Application.Models.Order", "Order")
                        .WithMany("OrderStatusHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.PaymentTransaction", b =>
                {
                    b.HasOne("OrderSalesService.Application.Models.Customer", "Customer")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderSalesService.Application.Models.Order", "Order")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.PromotionItem", b =>
                {
                    b.HasOne("OrderSalesService.Application.Models.Promotion", "Promotion")
                        .WithMany("PromotionItems")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.ReturnOrder", b =>
                {
                    b.HasOne("OrderSalesService.Application.Models.Order", "Order")
                        .WithMany("ReturnOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.ReturnOrderDetail", b =>
                {
                    b.HasOne("OrderSalesService.Application.Models.ReturnOrder", "ReturnOrder")
                        .WithMany("ReturnOrderDetails")
                        .HasForeignKey("ReturnOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnOrder");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.CustomerGroup", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderStatusHistories");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("ReturnOrders");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.Promotion", b =>
                {
                    b.Navigation("PromotionItems");
                });

            modelBuilder.Entity("OrderSalesService.Application.Models.ReturnOrder", b =>
                {
                    b.Navigation("ReturnOrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
