// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductInventoryService.Infrastructure.Data;

#nullable disable

namespace ProductInventoryService.Infrastructure.Migrations
{
    [DbContext(typeof(ProductInventoryDbContext))]
    [Migration("20260626142527_AddProductPriceHistory")]
    partial class AddProductPriceHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductInventoryService.Application.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Thực phẩm khô & Gia vị",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nước giải khát, Bia & Nước suối",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sữa & Sản phẩm từ sữa",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Bánh kẹo & Đồ ăn vặt",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Hóa mỹ phẩm & Chăm sóc cá nhân",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReceiptCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptCode")
                        .IsUnique()
                        .HasDatabaseName("IX_GoodsReceipts_ReceiptCode");

                    b.ToTable("GoodsReceipts", (string)null);
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.GoodsReceiptDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("ProductId");

                    b.ToTable("GoodsReceiptDetails", (string)null);
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxThreshold")
                        .HasColumnType("int");

                    b.Property<int>("MinThreshold")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_Inventories_ProductId");

                    b.ToTable("Inventories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0010001-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0010001-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0010002-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0010002-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0010003-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0010003-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0010004-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0010004-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0010005-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0010005-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0010006-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0010006-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0010007-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0010007-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0010008-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0010008-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0020001-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0020001-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0020002-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0020002-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0020003-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0020003-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0020004-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0020004-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0020005-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0020005-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0020006-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0020006-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0020007-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0020007-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0020008-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0020008-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0030001-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0030001-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0030002-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0030002-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0030003-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0030003-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0030004-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0030004-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0030005-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0030005-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0040001-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0040001-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0040002-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0040002-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0040003-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0040003-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0040004-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0040004-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0040005-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0040005-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0040006-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0040006-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0050001-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0050001-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0050002-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0050002-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0050003-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0050003-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0050004-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0050004-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0050005-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0050005-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0050006-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0050006-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        },
                        new
                        {
                            Id = new Guid("e0050007-1111-2222-3333-444455556666"),
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxThreshold = 1000,
                            MinThreshold = 10,
                            ProductId = new Guid("f0050007-1111-2222-3333-444455556666"),
                            QuantityOnHand = 100,
                            QuantityReserved = 0
                        });
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("int");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "CreatedAt")
                        .HasDatabaseName("IX_InventoryTransactions_ProductId_CreatedAt");

                    b.ToTable("InventoryTransactions", (string)null);
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.ProcessedEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedEvents", (string)null);
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("IX_Products_Barcode");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Code");

                    b.HasIndex("UnitId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0010001-1111-2222-3333-444455556666"),
                            Barcode = "8934563138162",
                            CategoryId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Code = "TP-MHH",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mì ăn liền Hảo Hảo tôm chua cay 75g",
                            ImportPrice = 3200m,
                            IsActive = true,
                            Name = "Mì ăn liền Hảo Hảo tôm chua cay 75g",
                            SellPrice = 4000m,
                            UnitId = new Guid("40c5f2b8-bd2e-4b20-8b1e-7f61b021c324"),
                            Weight = 0.075m
                        },
                        new
                        {
                            Id = new Guid("f0010002-1111-2222-3333-444455556666"),
                            Barcode = "8936011381014",
                            CategoryId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Code = "TP-DAS",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dầu ăn Simply nguyên chất 1L",
                            ImportPrice = 42000m,
                            IsActive = true,
                            Name = "Dầu ăn Simply nguyên chất 1L",
                            SellPrice = 52000m,
                            UnitId = new Guid("6b8703a9-23d9-483e-cf95-8b2b3c4d5e6f"),
                            Weight = 0.900m
                        },
                        new
                        {
                            Id = new Guid("f0010003-1111-2222-3333-444455556666"),
                            Barcode = "8936017362352",
                            CategoryId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Code = "TP-TCS",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tương ớt Chinsu chai 250g",
                            ImportPrice = 10500m,
                            IsActive = true,
                            Name = "Tương ớt Chinsu chai 250g",
                            SellPrice = 14000m,
                            UnitId = new Guid("6b8703a9-23d9-483e-cf95-8b2b3c4d5e6f"),
                            Weight = 0.250m
                        },
                        new
                        {
                            Id = new Guid("f0010004-1111-2222-3333-444455556666"),
                            Barcode = "8936017368026",
                            CategoryId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Code = "TP-NMNN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nước mắm Nam Ngư 3 trong 1 chai 750ml",
                            ImportPrice = 32000m,
                            IsActive = true,
                            Name = "Nước mắm Nam Ngư 3 trong 1 chai 750ml",
                            SellPrice = 39000m,
                            UnitId = new Guid("6b8703a9-23d9-483e-cf95-8b2b3c4d5e6f"),
                            Weight = 0.750m
                        },
                        new
                        {
                            Id = new Guid("f0010005-1111-2222-3333-444455556666"),
                            Barcode = "8934839111815",
                            CategoryId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Code = "TP-HNKN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hạt nêm Knorr Thịt thăn Xương ống 400g",
                            ImportPrice = 28000m,
                            IsActive = true,
                            Name = "Hạt nêm Knorr Thịt thăn Xương ống 400g",
                            SellPrice = 34000m,
                            UnitId = new Guid("40c5f2b8-bd2e-4b20-8b1e-7f61b021c324"),
                            Weight = 0.400m
                        },
                        new
                        {
                            Id = new Guid("f0010006-1111-2222-3333-444455556666"),
                            Barcode = "8938508216010",
                            CategoryId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Code = "TP-GAO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gạo thơm Jasmine thượng hạng túi 5kg",
                            ImportPrice = 105000m,
                            IsActive = true,
                            Name = "Gạo thơm Jasmine thượng hạng túi 5kg",
                            SellPrice = 125000m,
                            UnitId = new Guid("8d6905c1-45fb-4a50-ef17-0d4b5c6d7e8f"),
                            Weight = 5.000m
                        },
                        new
                        {
                            Id = new Guid("f0010007-1111-2222-3333-444455556666"),
                            Barcode = "8936017369016",
                            CategoryId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Code = "TP-MKK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mì gói Kokomi Đại 90 Tôm Chua Cay",
                            ImportPrice = 2800m,
                            IsActive = true,
                            Name = "Mì gói Kokomi Đại 90 Tôm Chua Cay",
                            SellPrice = 3500m,
                            UnitId = new Guid("40c5f2b8-bd2e-4b20-8b1e-7f61b021c324"),
                            Weight = 0.090m
                        },
                        new
                        {
                            Id = new Guid("f0010008-1111-2222-3333-444455556666"),
                            Barcode = "8935041200055",
                            CategoryId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Code = "TP-MUOI",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Muối tinh sấy i-ốt Visalco 500g",
                            ImportPrice = 4000m,
                            IsActive = true,
                            Name = "Muối tinh sấy i-ốt Visalco 500g",
                            SellPrice = 6000m,
                            UnitId = new Guid("40c5f2b8-bd2e-4b20-8b1e-7f61b021c324"),
                            Weight = 0.500m
                        },
                        new
                        {
                            Id = new Guid("f0020001-1111-2222-3333-444455556666"),
                            Barcode = "8935049500461",
                            CategoryId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Code = "NG-COCA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nước ngọt Coca Cola lon 320ml",
                            ImportPrice = 8000m,
                            IsActive = true,
                            Name = "Nước ngọt Coca Cola lon 320ml",
                            SellPrice = 10000m,
                            UnitId = new Guid("5a9602a8-12c8-472d-bf84-7a1a2b3c4d5e"),
                            Weight = 0.320m
                        },
                        new
                        {
                            Id = new Guid("f0020002-1111-2222-3333-444455556666"),
                            Barcode = "8934822201332",
                            CategoryId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Code = "NG-KEN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bia Heineken Silver lon 330ml",
                            ImportPrice = 16000m,
                            IsActive = true,
                            Name = "Bia Heineken Silver lon 330ml",
                            SellPrice = 20000m,
                            UnitId = new Guid("5a9602a8-12c8-472d-bf84-7a1a2b3c4d5e"),
                            Weight = 0.330m
                        },
                        new
                        {
                            Id = new Guid("f0020003-1111-2222-3333-444455556666"),
                            Barcode = "8935026810019",
                            CategoryId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Code = "NG-LAVIE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nước khoáng thiên nhiên La Vie 500ml",
                            ImportPrice = 4000m,
                            IsActive = true,
                            Name = "Nước khoáng thiên nhiên La Vie 500ml",
                            SellPrice = 6000m,
                            UnitId = new Guid("6b8703a9-23d9-483e-cf95-8b2b3c4d5e6f"),
                            Weight = 0.500m
                        },
                        new
                        {
                            Id = new Guid("f0020004-1111-2222-3333-444455556666"),
                            Barcode = "8938502391010",
                            CategoryId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Code = "NG-PEPSI",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nước ngọt Pepsi lon 320ml",
                            ImportPrice = 7800m,
                            IsActive = true,
                            Name = "Nước ngọt Pepsi lon 320ml",
                            SellPrice = 9500m,
                            UnitId = new Guid("5a9602a8-12c8-472d-bf84-7a1a2b3c4d5e"),
                            Weight = 0.320m
                        },
                        new
                        {
                            Id = new Guid("f0020005-1111-2222-3333-444455556666"),
                            Barcode = "8934822301339",
                            CategoryId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Code = "NG-TIGER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bia Tiger lon 330ml",
                            ImportPrice = 13500m,
                            IsActive = true,
                            Name = "Bia Tiger lon 330ml",
                            SellPrice = 17000m,
                            UnitId = new Guid("5a9602a8-12c8-472d-bf84-7a1a2b3c4d5e"),
                            Weight = 0.330m
                        },
                        new
                        {
                            Id = new Guid("f0020006-1111-2222-3333-444455556666"),
                            Barcode = "8851012110115",
                            CategoryId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Code = "NG-REDBULL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nước tăng lực Redbull lon 250ml",
                            ImportPrice = 10000m,
                            IsActive = true,
                            Name = "Nước tăng lực Redbull lon 250ml",
                            SellPrice = 12500m,
                            UnitId = new Guid("5a9602a8-12c8-472d-bf84-7a1a2b3c4d5e"),
                            Weight = 0.250m
                        },
                        new
                        {
                            Id = new Guid("f0020007-1111-2222-3333-444455556666"),
                            Barcode = "8936006030019",
                            CategoryId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Code = "NG-KHONGDO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trà xanh Không Độ 500ml",
                            ImportPrice = 7000m,
                            IsActive = true,
                            Name = "Trà xanh Không Độ 500ml",
                            SellPrice = 9000m,
                            UnitId = new Guid("6b8703a9-23d9-483e-cf95-8b2b3c4d5e6f"),
                            Weight = 0.500m
                        },
                        new
                        {
                            Id = new Guid("f0020008-1111-2222-3333-444455556666"),
                            Barcode = "8938502391034",
                            CategoryId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Code = "NG-7UP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nước ngọt 7Up lon 320ml",
                            ImportPrice = 7800m,
                            IsActive = true,
                            Name = "Nước ngọt 7Up lon 320ml",
                            SellPrice = 9500m,
                            UnitId = new Guid("5a9602a8-12c8-472d-bf84-7a1a2b3c4d5e"),
                            Weight = 0.320m
                        },
                        new
                        {
                            Id = new Guid("f0030001-1111-2222-3333-444455556666"),
                            Barcode = "8934673122457",
                            CategoryId = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"),
                            Code = "SU-VNM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sữa tươi tiệt trùng Vinamilk ít đường 180ml",
                            ImportPrice = 6500m,
                            IsActive = true,
                            Name = "Sữa tươi tiệt trùng Vinamilk ít đường 180ml",
                            SellPrice = 8500m,
                            UnitId = new Guid("7c7804b0-34ea-494f-df06-9c3b4c5d6e7f"),
                            Weight = 0.180m
                        },
                        new
                        {
                            Id = new Guid("f0030002-1111-2222-3333-444455556666"),
                            Barcode = "8936049080036",
                            CategoryId = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"),
                            Code = "SU-TH",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sữa tươi tiệt trùng TH True Milk ít đường 180ml",
                            ImportPrice = 6800m,
                            IsActive = true,
                            Name = "Sữa tươi tiệt trùng TH True Milk ít đường 180ml",
                            SellPrice = 9000m,
                            UnitId = new Guid("7c7804b0-34ea-494f-df06-9c3b4c5d6e7f"),
                            Weight = 0.180m
                        },
                        new
                        {
                            Id = new Guid("f0030003-1111-2222-3333-444455556666"),
                            Barcode = "8934804021200",
                            CategoryId = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"),
                            Code = "SU-MILO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sữa lúa mạch Nestlé Milo hộp 180ml",
                            ImportPrice = 7000m,
                            IsActive = true,
                            Name = "Sữa lúa mạch Nestlé Milo hộp 180ml",
                            SellPrice = 9200m,
                            UnitId = new Guid("7c7804b0-34ea-494f-df06-9c3b4c5d6e7f"),
                            Weight = 0.180m
                        },
                        new
                        {
                            Id = new Guid("f0030004-1111-2222-3333-444455556666"),
                            Barcode = "8934673130179",
                            CategoryId = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"),
                            Code = "SU-CHUA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sữa chua ăn Vinamilk có đường hộp 100g",
                            ImportPrice = 5000m,
                            IsActive = true,
                            Name = "Sữa chua ăn Vinamilk có đường hộp 100g",
                            SellPrice = 6500m,
                            UnitId = new Guid("7c7804b0-34ea-494f-df06-9c3b4c5d6e7f"),
                            Weight = 0.100m
                        },
                        new
                        {
                            Id = new Guid("f0030005-1111-2222-3333-444455556666"),
                            Barcode = "8934673120156",
                            CategoryId = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"),
                            Code = "SU-ONTHO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sữa đặc Ông Thọ đỏ lon 380g",
                            ImportPrice = 22000m,
                            IsActive = true,
                            Name = "Sữa đặc Ông Thọ đỏ lon 380g",
                            SellPrice = 26000m,
                            UnitId = new Guid("5a9602a8-12c8-472d-bf84-7a1a2b3c4d5e"),
                            Weight = 0.380m
                        },
                        new
                        {
                            Id = new Guid("f0040001-1111-2222-3333-444455556666"),
                            Barcode = "8934681144007",
                            CategoryId = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            Code = "BK-COSY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bánh quy Cosy Kinh Đô Marie gói 144g",
                            ImportPrice = 12000m,
                            IsActive = true,
                            Name = "Bánh quy Cosy Kinh Đô Marie gói 144g",
                            SellPrice = 16000m,
                            UnitId = new Guid("40c5f2b8-bd2e-4b20-8b1e-7f61b021c324"),
                            Weight = 0.144m
                        },
                        new
                        {
                            Id = new Guid("f0040002-1111-2222-3333-444455556666"),
                            Barcode = "8936079010123",
                            CategoryId = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            Code = "BK-LAYS",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khoai tây chiên Lay's vị tự nhiên gói 95g",
                            ImportPrice = 16000m,
                            IsActive = true,
                            Name = "Khoai tây chiên Lay's vị tự nhiên gói 95g",
                            SellPrice = 21000m,
                            UnitId = new Guid("40c5f2b8-bd2e-4b20-8b1e-7f61b021c324"),
                            Weight = 0.095m
                        },
                        new
                        {
                            Id = new Guid("f0040003-1111-2222-3333-444455556666"),
                            Barcode = "8936036010041",
                            CategoryId = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            Code = "BK-CHOCO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bánh ChocoPie Orion hộp 12 cái 396g",
                            ImportPrice = 44000m,
                            IsActive = true,
                            Name = "Bánh ChocoPie Orion hộp 12 cái 396g",
                            SellPrice = 55000m,
                            UnitId = new Guid("7c7804b0-34ea-494f-df06-9c3b4c5d6e7f"),
                            Weight = 0.396m
                        },
                        new
                        {
                            Id = new Guid("f0040004-1111-2222-3333-444455556666"),
                            Barcode = "4001686301524",
                            CategoryId = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            Code = "BK-HARIBO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kẹo dẻo Haribo Goldbears gói 80g",
                            ImportPrice = 22000m,
                            IsActive = true,
                            Name = "Kẹo dẻo Haribo Goldbears gói 80g",
                            SellPrice = 28000m,
                            UnitId = new Guid("40c5f2b8-bd2e-4b20-8b1e-7f61b021c324"),
                            Weight = 0.080m
                        },
                        new
                        {
                            Id = new Guid("f0040005-1111-2222-3333-444455556666"),
                            Barcode = "8886467100017",
                            CategoryId = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            Code = "BK-PRINGLES",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Snack khoai tây Pringles vị tự nhiên 110g",
                            ImportPrice = 32000m,
                            IsActive = true,
                            Name = "Snack khoai tây Pringles vị tự nhiên 110g",
                            SellPrice = 40000m,
                            UnitId = new Guid("7c7804b0-34ea-494f-df06-9c3b4c5d6e7f"),
                            Weight = 0.110m
                        },
                        new
                        {
                            Id = new Guid("f0040006-1111-2222-3333-444455556666"),
                            Barcode = "022000004944",
                            CategoryId = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            Code = "BK-GUM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kẹo cao su Doublemint sọc 5 tép",
                            ImportPrice = 4000m,
                            IsActive = true,
                            Name = "Kẹo cao su Doublemint sọc 5 tép",
                            SellPrice = 6000m,
                            UnitId = new Guid("40c5f2b8-bd2e-4b20-8b1e-7f61b021c324"),
                            Weight = 0.015m
                        },
                        new
                        {
                            Id = new Guid("f0050001-1111-2222-3333-444455556666"),
                            Barcode = "8934839130779",
                            CategoryId = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"),
                            Code = "HM-SL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nước rửa chén Sunlight chanh chai 750g",
                            ImportPrice = 24000m,
                            IsActive = true,
                            Name = "Nước rửa chén Sunlight chanh chai 750g",
                            SellPrice = 30000m,
                            UnitId = new Guid("6b8703a9-23d9-483e-cf95-8b2b3c4d5e6f"),
                            Weight = 0.750m
                        },
                        new
                        {
                            Id = new Guid("f0050002-1111-2222-3333-444455556666"),
                            Barcode = "8934839141089",
                            CategoryId = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"),
                            Code = "HM-OMO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bột giặt OMO Comfort tinh dầu thơm túi 3.6kg",
                            ImportPrice = 165000m,
                            IsActive = true,
                            Name = "Bột giặt OMO Comfort tinh dầu thơm túi 3.6kg",
                            SellPrice = 198000m,
                            UnitId = new Guid("8d6905c1-45fb-4a50-ef17-0d4b5c6d7e8f"),
                            Weight = 3.600m
                        },
                        new
                        {
                            Id = new Guid("f0050003-1111-2222-3333-444455556666"),
                            Barcode = "6901396340243",
                            CategoryId = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"),
                            Code = "HM-CG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kem đánh răng Colgate ngừa sâu răng 225g",
                            ImportPrice = 28000m,
                            IsActive = true,
                            Name = "Kem đánh răng Colgate ngừa sâu răng 225g",
                            SellPrice = 35000m,
                            UnitId = new Guid("7c7804b0-34ea-494f-df06-9c3b4c5d6e7f"),
                            Weight = 0.225m
                        },
                        new
                        {
                            Id = new Guid("f0050004-1111-2222-3333-444455556666"),
                            Barcode = "8934839154386",
                            CategoryId = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"),
                            Code = "HM-CLEAR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dầu gội Clear Bạc Hà thơm mát chai 630ml",
                            ImportPrice = 125000m,
                            IsActive = true,
                            Name = "Dầu gội Clear Bạc Hà thơm mát chai 630ml",
                            SellPrice = 149000m,
                            UnitId = new Guid("6b8703a9-23d9-483e-cf95-8b2b3c4d5e6f"),
                            Weight = 0.630m
                        },
                        new
                        {
                            Id = new Guid("f0050005-1111-2222-3333-444455556666"),
                            Barcode = "8934839129056",
                            CategoryId = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"),
                            Code = "HM-LIFEBUOY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sữa tắm Lifebuoy bảo vệ vượt trội chai 850g",
                            ImportPrice = 140000m,
                            IsActive = true,
                            Name = "Sữa tắm Lifebuoy bảo vệ vượt trội chai 850g",
                            SellPrice = 169000m,
                            UnitId = new Guid("6b8703a9-23d9-483e-cf95-8b2b3c4d5e6f"),
                            Weight = 0.850m
                        },
                        new
                        {
                            Id = new Guid("f0050006-1111-2222-3333-444455556666"),
                            Barcode = "8934839123016",
                            CategoryId = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"),
                            Code = "HM-LAUSAN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nước lau sàn Sunlight Hương Hoa thiên nhiên 1kg",
                            ImportPrice = 23000m,
                            IsActive = true,
                            Name = "Nước lau sàn Sunlight Hương Hoa thiên nhiên 1kg",
                            SellPrice = 29000m,
                            UnitId = new Guid("6b8703a9-23d9-483e-cf95-8b2b3c4d5e6f"),
                            Weight = 1.000m
                        },
                        new
                        {
                            Id = new Guid("f0050007-1111-2222-3333-444455556666"),
                            Barcode = "4902430882101",
                            CategoryId = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"),
                            Code = "HM-DOWNY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nước xả vải Downy Huyền Bí túi 1.6L",
                            ImportPrice = 110000m,
                            IsActive = true,
                            Name = "Nước xả vải Downy Huyền Bí túi 1.6L",
                            SellPrice = 135000m,
                            UnitId = new Guid("8d6905c1-45fb-4a50-ef17-0d4b5c6d7e8f"),
                            Weight = 1.600m
                        });
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.ProductPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("NewImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewSellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldSellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPriceHistories", (string)null);
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.StocktakeLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CountedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("StocktakeSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SystemQuantity")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VarianceQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StocktakeSessionId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_StocktakeLines_Session_Product");

                    b.ToTable("StocktakeLines", (string)null);
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.StocktakeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CountedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CountedItems")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StocktakeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.Property<int>("TotalVarianceQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StocktakeCode")
                        .IsUnique()
                        .HasDatabaseName("IX_StocktakeSessions_StocktakeCode");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("IX_StocktakeSessions_Status_StartedAt");

                    b.ToTable("StocktakeSessions", (string)null);
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40c5f2b8-bd2e-4b20-8b1e-7f61b021c324"),
                            Abbreviation = "gói",
                            IsActive = true,
                            Name = "Gói"
                        },
                        new
                        {
                            Id = new Guid("5a9602a8-12c8-472d-bf84-7a1a2b3c4d5e"),
                            Abbreviation = "lon",
                            IsActive = true,
                            Name = "Lon"
                        },
                        new
                        {
                            Id = new Guid("6b8703a9-23d9-483e-cf95-8b2b3c4d5e6f"),
                            Abbreviation = "chai",
                            IsActive = true,
                            Name = "Chai"
                        },
                        new
                        {
                            Id = new Guid("7c7804b0-34ea-494f-df06-9c3b4c5d6e7f"),
                            Abbreviation = "hộp",
                            IsActive = true,
                            Name = "Hộp"
                        },
                        new
                        {
                            Id = new Guid("8d6905c1-45fb-4a50-ef17-0d4b5c6d7e8f"),
                            Abbreviation = "túi",
                            IsActive = true,
                            Name = "Túi"
                        },
                        new
                        {
                            Id = new Guid("9e5a06d2-56fc-4b61-ff28-1e5b6c7d8e9f"),
                            Abbreviation = "hũ",
                            IsActive = true,
                            Name = "Hũ"
                        });
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.UnitConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("FromUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FromUnitId");

                    b.HasIndex("ToUnitId");

                    b.HasIndex("ProductId", "FromUnitId", "ToUnitId")
                        .IsUnique()
                        .HasDatabaseName("IX_UnitConversions_Product_From_To");

                    b.ToTable("UnitConversions", (string)null);
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.Category", b =>
                {
                    b.HasOne("ProductInventoryService.Application.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.GoodsReceiptDetail", b =>
                {
                    b.HasOne("ProductInventoryService.Application.Models.GoodsReceipt", "GoodsReceipt")
                        .WithMany("GoodsReceiptDetails")
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductInventoryService.Application.Models.Product", "Product")
                        .WithMany("GoodsReceiptDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.Inventory", b =>
                {
                    b.HasOne("ProductInventoryService.Application.Models.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("ProductInventoryService.Application.Models.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.InventoryTransaction", b =>
                {
                    b.HasOne("ProductInventoryService.Application.Models.Product", "Product")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.Product", b =>
                {
                    b.HasOne("ProductInventoryService.Application.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductInventoryService.Application.Models.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.ProductPriceHistory", b =>
                {
                    b.HasOne("ProductInventoryService.Application.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.StocktakeLine", b =>
                {
                    b.HasOne("ProductInventoryService.Application.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductInventoryService.Application.Models.StocktakeSession", "StocktakeSession")
                        .WithMany("Lines")
                        .HasForeignKey("StocktakeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StocktakeSession");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.UnitConversion", b =>
                {
                    b.HasOne("ProductInventoryService.Application.Models.Unit", "FromUnit")
                        .WithMany()
                        .HasForeignKey("FromUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductInventoryService.Application.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductInventoryService.Application.Models.Unit", "ToUnit")
                        .WithMany()
                        .HasForeignKey("ToUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUnit");

                    b.Navigation("Product");

                    b.Navigation("ToUnit");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.GoodsReceipt", b =>
                {
                    b.Navigation("GoodsReceiptDetails");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.Product", b =>
                {
                    b.Navigation("GoodsReceiptDetails");

                    b.Navigation("Inventory");

                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.StocktakeSession", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ProductInventoryService.Application.Models.Unit", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
